### PR TITLE
Removed opening/creating cache FS in optimize to make it compatible …

### PR DESCRIPTION
**Pull request by pnyczyk**
…with dask distributed (pickle error)

### CODE REVIEW

**Comment by lsorber** [comment]
Hi Piotr, thanks for the PR! We're aware of the issue, but unfortunately, this change is not ideal in a single-process environment because it leads to the creation of a lot of filesystems.

We checked if adding a custom distributed serialiser [1] based on cloudpickle [2] might solve the issue, but it doesn't unfortunately.

The next best solution is detecting which scheduler is or will be active, and if it is single process then open the FS up front, else lazily load it. We'll launch a quick PR to get that fixed.

[1] http://distributed.dask.org/en/latest/serialization.html#extend
[2] https://github.com/cloudpipe/cloudpickle

**Comment by pnyczyk** [comment]
Hi Laurent, please check this out. Instead of creating a single instance of the FS upfront in optimize I create a proxy instance CacheFS which creates and delivers a single instance of FS lazily. I tested it with dask.multiprocess, checked the id of cache_fs property of all the nodes in the optimized graph, checked with cloudpickle that I can pickle the graph, and it all seem to do the job.

**Comment by lsorber** [comment]
That's a clever solution, thanks! And it's also is a good step forward for solving #38.

Is this PR ready to merge for you, or did you want to add/change anything else?

**Comment by pnyczyk** [comment]
You're welcome, and thanks for this nice piece of software! It helps us a lot in the project we are currently working on.
For me this PR is ready to merge right now. In longer term, and in relation to #38 we'd like to be able to use an arbitrary key-value store, for example memcached. But it as the filesystem based storage works fine for now, there is no such priority, so we'll get back to it later.

**Pull request merged**
